databases:
  - name: site
    databaseName: tramline_site_production
    user: tramline
    postgresMajorVersion: 14

services:
  - type: web
    name: site
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false