previewsEnabled: true
previewsExpireAfterDays: 7
databases:
  - name: site-db
    databaseName: tramline_site_production
    user: tramline
    postgresMajorVersion: 14
    region: frankfurt

services:
  - type: web
    name: site-web
    env: ruby
    region: frankfurt
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec puma -C config/puma.rb"
    initialDeployHook: ./bin/render-seed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: site-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
