:verbose: true
:concurrency: 2
:timeout: 25
:queues:
  - ["high", 3]
  - ["medium", 2]
  - ["low", 1]

:schedule:
  kickoff:
    every: "1m"
    class: KickoffJob
    description: "This job finds trains or train-steps to jump-start"
    queue: high

production:
  :concurrency: 5

staging:
  :concurrency: 2